### ISSUE TITLE
Without context menu

### ISSUE THREAD

**Issue by ichigotake** [rejasupotaro/Rebuild#35]
タップ数を減らしたい、アクションバーは一応空いてはいる、ならばコンテキストメニューを排除してもよいのでは、と思う次第

いきなりパッチを送ろうかとも思いましたが、まずはどういった理由でコンテキストメニューを選択したかの理由が気になるところです

**Comment by ichigotake** [comment]
よく考えると、clear cacheが文字ではなくなるとややこしくなりそうですね

(さっきはTwitterのタイムライン画面をみてました

**Comment by rejasupotaro** [comment]
設定に関しては、設定はユーザに積極的に見せたいものでもないので、一段奥に置いています。
エピソードのダウンロード・キャッシュの削除に関しては、この状態が最適とは思ってなくて、導線の位置を変える予定です。

**Comment by ichigotake** [comment]
> 設定に関しては、設定はユーザに積極的に見せたいものでもないので、一段奥に置いています。

なるほど確かにそうですね

> エピソードのダウンロード・キャッシュの削除に関しては、この状態が最適とは思ってなくて、導線の位置を変える予定です。

わかりました！

疑問は解決しました、ありがとうございます

**Comment by hotchemi** [comment]
キャッシュが膨れ上がる事があるので、キャッシュ一括削除機能が欲しいです:eyes:

**Comment by rejasupotaro** [comment]
それは聴き終わったエピソードを削除したいということ？
キャッシュをしてあるけど、最後まで再生したらキャッシュを削除するアプリとかあるね。

聴いてる聴いてないに関わらず削除したいということは、端末の設定画面で容量が一杯になってるときに気付くケースが多いかなと思ってて、そのケースだとアプリ内じゃなくて設定画面からキャッシュを削除すればいいかなって思いました。

個人的には、基本エピソードは聴いたら消えていいんだけど、このエピソードだけ何回も聴きたいので取っておきたいっていうのはあるので、キャッシュが膨れ上がる問題に対しては一括削除より個別のキャッシュの削除をやりやすくするっていうアプローチが取りたいなと思ってます。(手が回っていないのだけど…)

**Comment by harupong** [comment]
エピソードのキャッシュの話が出たので便乗コメントです。Pocket Casts などの iOS のアプリで見られる
- 最新 n 回分 のキャッシュを保持(n は設定できる)
- Favorite した回はずっとキャッシュを保持

という機能だと、
- 一話ずつ手動で消す手間がない
- 古いエピソードは勝手に消えるのでキャッシュが膨れ上がる心配もない
- 何回も聴きたいエピソードのキャッシュを明示的に保持できる

ので気に入ってます。

発生頻度の多い「キャッシュ削除」が自動化されてて、たまにある「これ取っておきたい」が手動の方がユーザーとしては楽で嬉しいです。

**Comment by rejasupotaro** [comment]
返信遅くなってすいません。

> - 最新 n 回分 のキャッシュを保持(n は設定できる)
> - Favorite した回はずっとキャッシュを保持

これいいですね。ぜひとも導入したい所存。

**Comment by harupong** [comment]
:fireworks: 楽しみにしております！
