### ISSUE TITLE
Support aftershow episodes

### ISSUE THREAD

**Issue by miyagawa** [rejasupotaro/Rebuild#38]
Just published an episode for ep45a and it doesn't seem to show up. There might be some kind of pattern match that ignores this episode.

Generally speaking, it would be great if arbitrary titled episodes and filenames are supported. For instance, if you supply an arbitrary Podcast RSS feed and the app should still work, and it's ok if the list of guests and show notes might be empty.

It would be painful for both you and me, to make a rule about the naming of titles and filenames and such.

Thanks,

**Comment by miyagawa** [comment]
Looks like the episodeID must be integer - https://github.com/rejasupotaro/Rebuild/blob/master/Rebuild/src/main/java/rejasupotaro/rebuild/models/Episode.java#L189

That's too bad, but was bound to happen sooner or later, since i was thinking of publishing SP2 previews in RSS feed as well :)

**Comment by rejasupotaro** [comment]
That's right. I responded to an issue: https://github.com/rejasupotaro/Rebuild/pull/39.
I migrated the episode table (change id's data type to TEXT), and uses title as it is received.

Thanks for reporting!
