### ISSUE TITLE
Update Play Store description to include "Unofficial"

### ISSUE THREAD

**Issue by miyagawa** [rejasupotaro/Rebuild#46]
Add the word "Unofficial" in the Google Play store description.

Thanks,

**Comment by rejasupotaro** [comment]
I changed the app title. It will take some time for the data to be updated.
![](https://f22d8ec08a40c1469665165637056f907068798a.googledrive.com/host/0B7lk-omdYfVCRWd3ZTQyZGVCaG8/title)

**Comment by miyagawa** [comment]
Thank you :)
